// Interface to define the structure of a Book object
export interface Book {

 // Unique identifier for the book (optional because it’s usually generated by the database)
  _id?: string;

  // Title of the book
  title: string;

  //Author of the book
  author: string;

  //Genre or category of the book (e.g., Fiction, History, Sci-Fi, etc.)
  genre: string;

  //Date when the book was published (stored as a string, usually ISO format: YYYY-MM-DD)
  publishedDate: string;
}
